services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/log:/var/lib/zookeeper/log
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=3
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
    networks:
      - shared_network

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:7.3.2
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "29091"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:29091,PLAINTEXT_HOST://localhost:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
    volumes:
      - ./data/kafka1:/var/lib/kafka/data
    networks:
      - shared_network

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:7.3.2
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "29092"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
    volumes:
      - ./data/kafka2:/var/lib/kafka/data
    networks:
      - shared_network

  kafka3:
    container_name: kafka3
    image: confluentinc/cp-kafka:7.3.2
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "29093"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:29093,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
    volumes:
      - ./data/kafka3:/var/lib/kafka/data
    networks:
      - shared_network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:29091,kafka2:29092,kafka3:29093
    networks:
      - shared_network

networks:
  shared_network:
    name: common_exchange_network
    external: true